### ISSUE TITLE
Ménage des dépôts

### ISSUE THREAD

**Issue by thomasfredericks** [Les-gars-d-la-table/Canevas-Cosmique#15]
Vos dépôts ont essentiellement le même nom; "prototype qqch"(ce sont probablement plus des tests qu'un prototype). Veuillez faire le ménage des dépôts en effaçant les désuets, en les combinant ou en leur donnant un nom plus clair.

**Comment by externalsip** [comment]
Modifié les noms des repository pour leurs donner des noms qui sont plus clairs par rapport à leurs contenu, je vais maintenant les archiver.
