### ISSUE TITLE
aruco > reactivision

### ISSUE THREAD

**Issue by gllmAR** [Les-gars-d-la-table/Canevas-Cosmique#2]
Après quelques tests de Reactivision, j'ai observé que le système de suivi est assez fragile et peu performant. Il nécessite une calibration dans un logiciel qui est relativement peu intuitif, surtout pour une modification adaptée à vos besoins.

Depuis le développement de Reactivision, de nombreux systèmes de suivi temps réel de fiduciaux ont vu le jour, offrant potentiellement de meilleures performances. Je pense en particulier à l'implémentation dans OpenCV du suivi de marqueurs ARUCO.

Diverses implémentations existent également dans d'autres langages que le C++. Par exemple, en JavaScript, vous pouvez trouver ici [js-aruco2](https://github.com/damianofalcioni/js-aruco2), avec une démonstration assez proche de ce que vous recherchez disponible sur [ce lien](https://damianofalcioni.github.io/js-aruco2/samples/debug/debug.html).

Il y a également un générateur de marqueurs accessible ici : [Générateur de marqueurs ARUCO](https://damianofalcioni.github.io/js-aruco2/samples/marker-creator/marker-creator.html?dictionary=ARUCO).

En outre, pour TouchDesigner, vous pouvez consulter [Aruco Markers Reader](https://derivative.ca/community-post/asset/aruco-markers-reader/65920).

Pour Unity (via OpenCV), ce paquet est disponible : [OpenCV Plus Unity](https://assetstore.unity.com/packages/tools/integration/opencv-plus-unity-85928).

Enfin, ce tutoriel sur OpenCV peut s'avérer utile : [Tutoriel de détection ARUCO avec OpenCV](https://docs.opencv.org/3.4/d5/dae/tutorial_aruco_detection.html).

**Comment by gllmAR** [comment]
Suggestion Thomas : 
https://solarframework.github.io/use/unity/

**Comment by externalsip** [comment]
La détection est maintenant  prise en charge sur TouchDesigner avec des marqueurs aruco.

**Comment by externalsip** [comment]
Les informations sont maintenant envoyées correctement vers Unity en OSC à partir de touchDesigner, il ne reste qu'à calibrer la table afin de pouvoir avoir les informations comme la rotation.
