### ISSUE TITLE
Caméra infrarouge ->  NDI

### ISSUE THREAD

**Issue by gllmAR** [Les-gars-d-la-table/Canevas-Cosmique#3]
Caméra (USB ou CSI ) dans raspberry pi qui stream un flux NDI 

```mermaid
graph TD;
    CAM_USB-->USB-->RASPBERRY;
    CAM_CSI-->CSI-->RASPBERRY;
    RASPBERRY --> DEV_VIDEO_2_NDI;
    ETHERNET_POE -->RASPBERRY;
    DEV_VIDEO_2_NDI --> NDI ----> TRACKING_CPU
```

**Comment by gllmAR** [comment]
Pour [DEV_VIDEO_2_NDI]
Une implémentation potentielle de ça pourrait fonctionner
https://gitlab.com/gllmar/gst-ndi-systemd/-/blob/main/gst-ndi-send.sh?ref_type=heads

**Comment by externalsip** [comment]
Kinect -> NDI
