### ISSUE TITLE
Réaliser un tableau d'interactions

### ISSUE THREAD

**Issue by thomasfredericks** [Les-gars-d-la-table/Canevas-Cosmique#4]
![image](https://github.com/Les-gars-d-la-table/Canevas-Cosmique/assets/2685516/210f4753-61ee-4369-8e17-dcbcb72ef371)

**Comment by externalsip** [comment]
![image](https://github.com/Les-gars-d-la-table/Canevas-Cosmique/assets/93773873/761843ce-e2ff-45db-b383-8c25586508c3)
tableau d'intéraction que nous avons créé.

**Comment by thomasfredericks** [comment]
produire un tableau de sons associés aux interactions
décrire chacun des sons
