### ISSUE TITLE
Développer l'esthétique sonore et visuelle

### ISSUE THREAD

**Issue by thomasfredericks** [Les-gars-d-la-table/Canevas-Cosmique#5]
Doom ou Minecraft?

**Comment by joeballls** [comment]
On a décidé pour le style visuel de rester avec le style Low Poly simple et de "simplifier" les textures en les pixelisant.
![Woah](https://github.com/Les-gars-d-la-table/Canevas-Cosmique/assets/74332549/d66a8f59-985a-4a46-9e27-e087980cb2b4)
![Woah2](https://github.com/Les-gars-d-la-table/Canevas-Cosmique/assets/74332549/0af43ad6-d7e6-439e-96a8-5aba6f5fc7fb)

**Comment by thomasfredericks** [comment]
@joeballls Puisque le _low poly_ n'utilise pas des textures pixelisées mais du _flat shading_, il va falloir que vous trouviez un _shader_ approprié.

La pixellisation fait partie d'une autre approche esthétique. 

![image](https://github.com/Les-gars-d-la-table/Canevas-Cosmique/assets/2685516/8e03a9df-1079-43be-b092-c9a30c1a04bc)
